### ISSUE TITLE
Enable in option --allow (IP whitelist) servername 

### ISSUE THREAD

**Issue by snk26** [ahebrank/gitlab-webhook-handler#11]
My gitlab moved to another server and I had to edit ip in the startup script. Please, add servername support.

**Comment by ahebrank** [comment]
Can you provide more information about the change you had to make?

**Comment by snk26** [comment]
-/opt/gitlab-webhook-handler/gwh.py -c /opt/gitlab-webhook-handler/repos.json -p 8080 --allow XXX.XXX.XXX.XXX
+/opt/gitlab-webhook-handler/gwh.py -c /opt/gitlab-webhook-handler/repos.json -p 8080 --allow XXX.XXX.XXX.YYY

Instead of the IP address, I would like to be able to specify the server name.

**Comment by ahebrank** [comment]
I see. This isn't really a valid option here since we can't rely on DNS to return the correct IP address. I think the better solution to validate the request is to start using hook tokens, which is an outstanding issue (#3).
