### ISSUE TITLE
Moving forward...

### ISSUE THREAD

**Issue by michael-o** [ahebrank/gitlab-webhook-handler#13]
Have you abandoned this project? I was desperately searching for such a module and forked this many years ago and am I using this very successfully with our inhouse GL instance.
I have done some necessary fixes: https://github.com/ahebrank/gitlab-webhook-handler/compare/master...michael-o:gitlab-webhook-handler:master

Should I continue with my fork? I'd like to turn this into a FreeBSD port in the future.

**Comment by ahebrank** [comment]
I'm happy to point folks to your fork if you're actively working on it. I haven't used this in many years (basically since Gitlab CI) so while not really abandoned I just don't have a good testbed to maintain it.

**Comment by michael-o** [comment]
Yes, I see. I use GitLab CI, but it does not replace the webhook for me sinc ein my setup the container needs to pull some from some remote orgins.

Would you be willing to accept a PR. I haven't done any change this then since it just works for me. Espeecially with Python 3.

**Comment by ahebrank** [comment]
Sure, go ahead. I'll take a look at it.

**Comment by ahebrank** [comment]
(also if you want to review #12 I'd really appreciate it)

**Comment by michael-o** [comment]
Done in https://github.com/ahebrank/gitlab-webhook-handler/pull/14

**Comment by ahebrank** [comment]
Thanks for contributing!

**Comment by michael-o** [comment]
Thank you for the quick turnaround. Will get back end of year when there is an issue with Python 3.8+.
