### ISSUE TITLE
Create setup.py or similar

### ISSUE THREAD

**Issue by michael-o** [ahebrank/gitlab-webhook-handler#21]
Thanks you for the quick turnaround
==========

To easily install this application to `site-packages` a `setup.py` or its successor would be nice. Since I heavily depend on this and want to turn this into a FreeBSD port as well, I will work on the required files and present a PR hopefully this month.

**Comment by ahebrank** [comment]
Thanks, sounds good. I haven't used this in many years so I appreciate someone taking an interest!
