### ISSUE TITLE
Raise versions in requirements.txt?

### ISSUE THREAD

**Issue by michael-o** [ahebrank/gitlab-webhook-handler#22]
Although these work:
https://github.com/ahebrank/gitlab-webhook-handler/blob/f73290743bd2293291f7315fc6cc9301f843a6bc/requirements.txt#L1-L2

I don't think it is reasonable to keep these since likely these versions no one will test anymore. I, at least, tested with the versions available throughout the last couple of years only and kept upgrading through the FreeBSD ports system.

Flask >= 1.x? 2.x?
requests >= 2.20.x?

WDYT?

**Comment by ahebrank** [comment]
Yep, please go ahead and update to whatever is relatively current.
