### ISSUE TITLE
Releasing version 1.0.0

### ISSUE THREAD

**Issue by michael-o** [ahebrank/gitlab-webhook-handler#29]
I'd like to discuss how we can get 1.0.0 out of the door as a GH release and ideally on PyPI. Copying from one MR:

* Create 1.0.0 (modify gwh/__version__.py to 1.0.0, commit, tag 1.0.0, run `python setup.py sdist`, create GH release and upload tarball from `sdist`
* Increment to 1.0.1.dev
* Publish to PyPI (don't know the process) from tag

How can I assist to make at least the first two points happen?

**Comment by michael-o** [comment]
@ahebrank Let me know when you can allocate some time for this since I can't do it myself.

**Comment by ahebrank** [comment]
OK, all set: https://pypi.org/project/gwh/

Versioning is based on creating a new release (well, really a new tag with semantic version number).

**Comment by michael-o** [comment]
Fantastic. Though, there is a bug. You missed to update `__version__.py`: https://github.com/ahebrank/gitlab-webhook-handler/blob/f84d7dbd45700db42b2354b70561d2230f0bac5e/gwh/__version__.py#L2 That is why I have added this single source of truth.
Output:
```
$ pip list | grep gwh && python3 -m gwh --version
gwh                    1.0.0
gitlab-webhook-handler 1.0.0.dev
```

I don't how the approriate release procedure for Python projects is, I come from Java world where the Maven Release Plugin does the following:
* Increment version to non-SNAPSHOT
* Tag from the currernt branch
* Increment version to SNAPSHOT
* Shallow clone from tag
* Release from tag

So here is the single source of truth the `pom.xml`.

**Comment by ahebrank** [comment]
I'm actually not using __version__.py so have removed it (see https://github.com/ahebrank/gitlab-webhook-handler/blob/master/setup.py#L6). The version is swapped in from the repo tag during the package build so doesn't live in the source, only in the artifact.

I'm not sure if this will cause trouble in a python package or not, but for now it seems to work and means I can do a release from the GH UI without editing the repo.

**Comment by michael-o** [comment]
Well, now `__main__.py` is broken: https://github.com/ahebrank/gitlab-webhook-handler/blob/6ef6ae77ef79a1f5a98f6453a83bf02fe7278629/gwh/__main__.py#L4-L14

As I said, I did it on purpose to wire it up and edit once.

why not modify `__version__.py` from the CI workflow and retain the rest as-is? That should work as well, no?
`develop` => `{tag}`

**Comment by michael-o** [comment]
I can provide a PR which restores status quo and still replaces the way you want in `__version__.py`. WDYT?

**Comment by ahebrank** [comment]
I've put this back, more or less. I didn't realize the version was used outside of setup.py.

**Comment by michael-o** [comment]
This looks better now, has one issue one needs to be aware of: If you build/install from the tag is still says 0.0.0:
```
osipovmi@deblndw011x:~/var/Projekte/gitlab-webhook-handler ((1.0.2) %)
$ python3 -m gwh --version
gwh 0.0.0
```
but this is something I can live with.

**Comment by michael-o** [comment]
Maybe I will look at this in the future: https://pypi.org/project/versioningit/
