### ISSUE TITLE
Add webhook secret token support

### ISSUE THREAD

**Issue by ahebrank** [ahebrank/gitlab-webhook-handler#3]
<img width="1003" alt="screen shot 2016-11-13 at 6 22 38 pm" src="https://cloud.githubusercontent.com/assets/5023646/20249761/49f9d428-a9ce-11e6-9550-e4cf969565a4.png">

**Comment by snk26** [comment]
I beg to implement this functionality

**Comment by ahebrank** [comment]
@snk26, can you verify that https://github.com/ahebrank/gitlab-webhook-handler/pull/12 works for you?
